// ⚠️ Auto-generated by scripts/apply-branding.mjs. Do not edit directly.
// To update branding, edit app.config.mjs and run: npm run brand

export const APP_NAME           = 'EasiestClaw'
export const APP_ID             = 'com.EasiestClaw.desktop'
export const FIREWALL_RULE_NAME = 'EasiestClaw'
